[package]
name = "linux_tun_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
simplelog = "0.12.1"
tokio = { version = "1.11.0", features = ["rt", "net", "rt-multi-thread", "time"] }
tun = { path = "../" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
