[package]
name = "tun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["io-util", "rt", "time"] }
log = "0.4.20"
rayon = "1.7"

[build-dependencies]
bindgen = "0.65.1"
